/* Test navigateur reproductible : npm run test:browser (après npx playwright install chromium). */
const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const root=path.resolve(__dirname,'..');const out=path.resolve(process.env.QA_OUTPUT||path.join(root,'qa-results'));fs.mkdirSync(out,{recursive:true});
async function main(){
 const server=require('../scripts/serve.cjs');if(!server.listening)await new Promise((r,j)=>{server.once('listening',r);server.once('error',j);});
 const args=['--no-sandbox','--disable-dev-shm-usage'];if(process.env.CHROMIUM_EXECUTABLE)args.push('--single-process','--no-zygote','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader');
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,args});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];const checks=[];page.on('pageerror',e=>errors.push(e.message));const base='http://localhost:'+Number(process.env.PORT||8080);
 const check=(name,fn)=>{assert(fn,name);checks.push(name);};
 const goto=async(route)=>{await page.goto(base+'/'+route);if(await page.locator('#page-root').count())await page.waitForFunction(()=>!document.querySelector('#page-root').hasAttribute('aria-busy'));if(await page.locator('body[data-static-layout]').count())await page.waitForFunction(()=>document.body.dataset.authState!=='pending');await page.evaluate(()=>document.fonts.ready);};
 const login=async(id)=>{await goto('auth/login.html');const email=await page.evaluate(id=>window.MongangaData.demoUsers().find(u=>u.id===id).email,id);await page.fill('#loginEmail',email);await page.fill('#loginPassword','Demo1234');await page.getByRole('button',{name:'Se connecter',exact:true}).click();await page.waitForURL('**/dashboard.html');await page.waitForFunction(()=>document.body.dataset.authState==='ready');};
 try{
  await goto('index.html');await page.screenshot({path:path.join(out,'accueil-desktop.png'),fullPage:true});check('Accueil : photo chargée seule',await page.locator('.hero-visual img').evaluate(img=>img.complete&&img.naturalWidth>0)&&await page.locator('.hero-visual').locator('img').count()===1);check('Accueil : aucun débordement',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await login('patient-demo');await goto('patient/search.html');await page.screenshot({path:path.join(out,'recherche-desktop.png'),fullPage:true});await page.fill('#doctor-search','Ilunga');await page.getByRole('button',{name:'Rechercher',exact:true}).click();check('Recherche filtrée',await page.locator('.doctor-card').count()===1);await page.getByRole('link',{name:'Voir le profil',exact:true}).click();await page.locator('input[name="slot"]').first().check();await page.getByRole('button',{name:'Continuer vers le paiement'}).click();await page.waitForURL('**/patient/payment.html?id=*');const bookingId=new URL(page.url()).searchParams.get('id');
  await page.fill('#phone','+243820000000');await page.check('#payment-consent');await page.getByRole('button',{name:'Tester le paiement',exact:true}).click();await page.getByRole('button',{name:'Simuler un échec'}).click();check('Échec visible, aucune fausse confirmation',await page.locator('.notice.danger:not([hidden])').textContent().then(t=>t.includes('échoué')));await page.fill('#phone','+243820000000');await page.check('#payment-consent');await page.getByRole('button',{name:'Tester le paiement',exact:true}).click();await page.getByRole('button',{name:'Simuler la réussite'}).click();await page.getByRole('heading',{name:'Votre rendez-vous est confirmé.'}).waitFor();check('Réservation confirmée après simulation explicite',true);
  await goto('patient/history.html');await page.locator(`[data-reschedule="${bookingId}"]`).click();await page.locator('dialog input[name="slot"]').nth(1).check();await page.getByRole('button',{name:'Confirmer le nouvel horaire'}).click();await page.waitForFunction(()=>!document.querySelector('dialog'));check('Déplacement confirmé sans deuxième paiement',await page.evaluate(id=>JSON.parse(sessionStorage.getItem('monganga-demo-v2')).transactions.filter(t=>t.bookingId===id).length===1,bookingId));
  await login('user-ilunga');await goto(`doctor/consult.html?id=${bookingId}`);await page.fill('#message','Bonjour, message de test.');await page.getByRole('button',{name:'Envoyer',exact:true}).click();await page.getByText('Bonjour, message de test.',{exact:false}).waitFor();check('Chat : message conservé',true);await page.getByRole('button',{name:'Terminer la consultation',exact:true}).click();await page.locator('dialog').getByRole('button',{name:'Terminer',exact:true}).click();await page.waitForURL('**/doctor/agenda.html');await goto('doctor/ordonnances.html');await page.getByRole('button',{name:'Nouvelle ordonnance'}).click();await page.selectOption('dialog #bookingId',bookingId);await page.fill('dialog #medication','Document fictif de recette');await page.fill('dialog #instructions','Exemple de validation de l’interface. Sans valeur médicale.');await page.getByRole('button',{name:'Enregistrer l’ordonnance'}).click();await page.waitForURL('**/doctor/ordonnances.html?id=*');check('Ordonnance médecin créée',await page.locator('.prescription-sheet').textContent().then(t=>t.includes('Document fictif')));
  await login('patient-demo');await goto('patient/prescription.html');check('Ordonnance disponible au patient',await page.locator('#rx-results').textContent().then(t=>t.includes('Document fictif')));await login('patient-second');await goto('patient/prescription.html');check('Autre patient : aucune ordonnance visible',await page.locator('.empty-state').count()===1);await goto(`patient/payment.html?id=${bookingId}`);check('Accès à un rendez-vous tiers refusé',await page.getByRole('heading',{name:'Chargement impossible'}).count()===1);
  await login('admin-demo');await goto('admin/transactions.html');const refund=page.locator('[data-refund]').first();await refund.click();await page.fill('dialog #reason','Recette du remboursement');await page.locator('dialog').getByRole('button',{name:'Confirmer',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('dialog'));check('Administration : remboursement visible',await page.locator('#transactions-results').textContent().then(t=>t.includes('Remboursé')));
  // Recette de chaque écran dynamique et public à plusieurs largeurs.
  const groups={public:['index.html','public/doctors.html','public/doctor.html?id=ilunga','public/how.html','public/pricing.html','public/faq.html','public/candidature.html','public/contact.html','public/conditions-utilisation.html','public/politique-confidentialite.html','public/mentions-legales.html','auth/login.html','auth/register.html','auth/forgot.html','auth/reset.html'],patient:['patient/dashboard.html','patient/search.html','patient/doctor.html?id=ilunga','patient/history.html','patient/prescription.html','patient/profile.html'],doctor:['doctor/dashboard.html','doctor/agenda.html','doctor/dispo.html','doctor/demandes.html','doctor/patients.html','doctor/ordonnances.html','doctor/gains.html','doctor/profile.html'],admin:['admin/dashboard.html','admin/users.html','admin/validations.html','admin/transactions.html','admin/reports.html']};
  for(const [role,routes]of Object.entries(groups)){if(role!=='public')await login({patient:'patient-demo',doctor:'user-ilunga',admin:'admin-demo'}[role]);for(const width of [360,768,1024,1440]){await page.setViewportSize({width,height:900});for(const route of routes){await goto(route);check(`${route} à ${width}px : contenu`,await page.locator('h1').count()===1);check(`${route} à ${width}px : sans débordement`,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));if(route==='patient/search.html'&&width===360)await page.screenshot({path:path.join(out,'recherche-mobile.png'),fullPage:true});}}}
  await page.setViewportSize({width:390,height:844});await login('patient-demo');await goto('patient/search.html');await page.getByRole('button',{name:'Menu',exact:true}).click();check('Menu mobile ouvert',await page.locator('#patMenu').evaluate(e=>e.classList.contains('active')));await page.keyboard.press('Escape');check('Échap ferme le menu',!await page.locator('#patMenu').evaluate(e=>e.classList.contains('active')));await page.getByRole('button',{name:/Activer le thème sombre/}).click();check('Thème sombre appliqué',await page.locator('html').getAttribute('data-theme')==='dark');await page.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));await page.screenshot({path:path.join(out,'recherche-mobile-sombre.png'),fullPage:true});await page.reload();check('Thème persistant',await page.locator('html').getAttribute('data-theme')==='dark');
  await goto('public/faq.html');const first=page.locator('.faq-question').first();await first.focus();await page.keyboard.press('Enter');check('FAQ utilisable au clavier',await first.getAttribute('aria-expanded')==='true');
  check('Aucune erreur JavaScript non gérée',errors.length===0);
  // Mode réel simulé par un serveur de recette : une panne ne doit jamais afficher de médecins fictifs.
  await page.route('**/assets/js/config.js',route=>route.fulfill({contentType:'application/javascript',body:"window.MONGANGA_CONFIG={mode:'api',apiBaseUrl:'/api/v1',timeoutMs:500};"}));await page.route('**/api/v1/doctors',route=>route.fulfill({status:503,contentType:'application/json',body:'{"message":"Indisponible"}'}));await goto('public/doctors.html');check('API en panne : erreur et nouvelle tentative',await page.getByRole('button',{name:'Réessayer',exact:true}).count()===1&&await page.locator('.doctor-card').count()===0);
  fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({passed:checks.length,checks,errors},null,2));console.log(`Navigateur : ${checks.length} vérifications réussies, ${errors.length} erreur JavaScript.`);
 }catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true}).catch(()=>{});console.error('URL en échec : '+page.url());throw e;}finally{await browser.close();await new Promise(r=>server.close(r));}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
