/* Régression ciblée : conserver les mises en page et les parcours d’authentification. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{
 const server=require('../scripts/serve.cjs');if(!server.listening)await new Promise(r=>server.once('listening',r));
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,args:process.env.CHROMIUM_EXECUTABLE?['--no-sandbox','--single-process','--no-zygote','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']:[]});
 const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),base='http://localhost:'+Number(process.env.PORT||8080),errors=[];
 const out=path.resolve(process.env.QA_OUTPUT||'qa-results','restoration');fs.mkdirSync(out,{recursive:true});page.on('pageerror',e=>errors.push(e.message));
 const goto=async route=>{await page.goto(base+'/'+route);await page.waitForFunction(()=>document.body.dataset.authState==='ready');await page.evaluate(()=>document.fonts.ready);};
 const shot=async name=>page.screenshot({path:path.join(out,name+'.png'),fullPage:true,animations:'disabled'});
 const demo=async id=>{await goto('auth/login.html');await page.locator(`[data-demo-id="${id}"]`).click();await page.getByRole('button',{name:'Se connecter',exact:true}).click();await page.waitForURL('**/dashboard.html');await page.waitForFunction(()=>document.body.dataset.authState==='ready');};
 try{
  await goto('auth/login.html');assert.equal(await page.locator('.app-header').count(),0);assert.equal(await page.locator('.auth-card').evaluate(e=>Math.round(e.getBoundingClientRect().width)),440);assert.equal(await page.locator('.auth-card').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(255, 255, 255)');await shot('connexion');
  await page.fill('#loginEmail','admin-inconnu@example.test');await page.fill('#loginPassword','Demo1234');await page.getByRole('button',{name:'Se connecter',exact:true}).click();await page.locator('.form-error:not([hidden])').waitFor();assert(page.url().endsWith('/auth/login.html'));
  await demo('user-ilunga');assert.equal(await page.locator('.doctor-sidebar').evaluate(e=>e.getBoundingClientRect().x),0);assert.deepEqual(await page.locator('.card-title').allTextContents(),['Agenda du jour','Demandes reçues','Performance','Actions rapides','Patients récents']);await shot('dashboard-medecin');await page.selectOption('#performance-period','week');assert.equal(await page.locator('.bar-col').count(),7);
  await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Menu',exact:true}).click();assert.equal(await page.locator('.doctor-sidebar').getAttribute('aria-modal'),'true');assert(await page.locator('main').evaluate(e=>e.inert));await page.keyboard.press('Escape');assert(await page.locator('.doctor-sidebar').evaluate(e=>e.inert));assert(!await page.locator('main').evaluate(e=>e.inert));await shot('dashboard-medecin-mobile');
  await page.setViewportSize({width:1440,height:1000});await demo('admin-demo');assert.deepEqual(await page.locator('.card-title').allTextContents(),['Croissance utilisateurs','Activités récentes','Performance globale','Alertes opérationnelles','Journal système']);await shot('dashboard-admin');
  await demo('patient-demo');assert.equal(await page.locator('.pat-nav').count(),1);assert.equal(await page.locator('.kpi-card').count(),4);await shot('dashboard-patient');
  await goto('auth/register.html');await shot('inscription-patient');await page.getByRole('tab',{name:'Médecin',exact:true}).click();assert(await page.locator('#form-doctor').isVisible());assert(!await page.locator('#form-patient').isVisible());await shot('inscription-medecin');await page.keyboard.press('ArrowLeft');assert(await page.locator('#form-patient').isVisible());
  await page.fill('#firstName','Marie');await page.fill('#lastName','Test');await page.fill('#phone','+243820003333');await page.fill('#password-patient','Test1234');await page.getByRole('button',{name:'Afficher le mot de passe'}).click();assert.equal(await page.locator('#password-patient').getAttribute('type'),'text');await page.check('#consent');await page.getByRole('button',{name:'Créer mon compte patient'}).click();await page.waitForURL('**/auth/verify.html');await page.fill('#code','000000');await page.getByRole('button',{name:'Valider mon numéro'}).click();await page.locator('.form-error:not([hidden])').waitFor();await page.fill('#code','123456');await page.getByRole('button',{name:'Valider mon numéro'}).click();await page.waitForURL('**/patient/dashboard.html');await page.getByRole('heading',{name:'Bonjour Marie 👋'}).waitFor();
  await goto('auth/forgot.html');await page.fill('#identifier','+243820003333');await page.getByRole('button',{name:'Envoyer le lien'}).click();await page.locator('.form-error:not([hidden])').waitFor();assert.equal(await page.locator('#forgot-form').count(),1);
  await goto('public/faq.html');await shot('faq');await page.locator('.faq-question').first().focus();await page.keyboard.press('Enter');assert.equal(await page.locator('.faq-question').first().getAttribute('aria-expanded'),'true');await page.locator('[data-filter="paiement"]').click();assert.equal(await page.locator('.faq-item:visible').count(),1);
  await goto('public/how.html');await shot('comment-ca-marche');
  await page.setViewportSize({width:390,height:844});for(const route of ['auth/login.html','auth/register.html','public/faq.html','public/how.html']){await goto(route);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await shot(route.replaceAll('/','-').replace('.html','')+'-mobile');}
  let rejected=true,request;
  await page.route('**/assets/js/config.js',r=>r.fulfill({contentType:'application/javascript',body:"window.MONGANGA_CONFIG={mode:'api',apiBaseUrl:'/api/v1',timeoutMs:2000};"}));
  const session={id:'api-patient',name:'Marie API',email:'',role:'patient',expiresAt:new Date(Date.now()+3600000).toISOString()};
  await page.route('**/api/v1/**',async r=>{const route=new URL(r.request().url()).pathname;let payload;if(route.endsWith('/auth/csrf'))payload={csrfToken:'test-token'};else if(route.endsWith('/auth/login')){request=r.request().postDataJSON();if(rejected)return r.fulfill({status:401,contentType:'application/json',body:'{"code":"INVALID_CREDENTIALS"}'});payload=session;}else if(route.endsWith('/auth/me'))payload=session;else payload=[];return r.fulfill({contentType:'application/json',body:JSON.stringify(payload)});});
  await goto('auth/login.html');assert(!await page.locator('.demo-hint').isVisible());await page.fill('#loginEmail','+243820003333');await page.fill('#loginPassword','Test1234');await page.check('[name="remember"]');await page.getByRole('button',{name:'Se connecter',exact:true}).click();await page.locator('.form-error:not([hidden])').waitFor();assert((await page.locator('.form-error').textContent()).includes('Identifiant ou mot de passe incorrect'));assert.equal(request.identifier,'+243820003333');assert.equal(request.remember,true);rejected=false;await page.getByRole('button',{name:'Se connecter',exact:true}).click();await page.waitForURL('**/patient/dashboard.html');await page.getByRole('heading',{name:'Bonjour Marie 👋'}).waitFor();assert.equal(await page.locator('#mode-indicator').isVisible(),false);
  assert.deepEqual(errors,[]);console.log('Restauration : structures, graphiques, menus, onglets, inscription sans email, OTP, erreurs et connexion API vérifiés.');
 }catch(e){await shot('echec');console.error('Page : '+page.url());throw e;}finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
